language: julia

julia:
  - 1.0
  - 1.5
  - 1.6
  - nightly

os:
  - linux
  - osx
  - windows
  
jobs:
  allow_failures:
    - julia: nightly
    - julia: 1.6
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ -e 'using Pkg; Pkg.build("PDFIO"); include("docs/make.jl")'
      after_success: skip  

notifications:
  email: false

after_success:
  - julia -e 'import PDFIO; cd(joinpath(dirname(pathof(PDFIO)), "..")); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
 
